### ISSUE TITLE
可否优化下你的邮箱的自动回复？

### ISSUE THREAD

**Issue by mzlogin** [QinZXX/QinZXX#1]
在你曾经参与过的 Issue 或者 Discussions 里，如果有人回复，你的邮箱自动回复就会触发，比如：

https://github.com/mzlogin/blog-comments/discussions/204

建议配置取消配置邮件自动回复，或者优化下自动回复的规则哈～多谢！

**Comment by mzlogin** [comment]
截图：

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/1646590/198009380-86de370c-320b-4072-9c55-cb49a243db91.png">

**Comment by QinZXX** [comment]
好的收到，我稍后回家修改下哈，不好意思



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月26日(周三) 晚上6:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [QinZXX/QinZXX] 可否优化下你的邮箱的自动回复？ (Issue #1)




 
截图：

**Comment by QinZXX** [comment]
已更新，不好意思之前忘记了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QinZXX/QinZXX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 晚上7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QinZXX/QinZXX] 可否优化下你的邮箱的自动回复？ (Issue #1)





 
Closed #1 as completed.

**Comment by mzlogin** [comment]
嗯嗯 没事，解决了就好啦～
